DROP TABLE RANKING_EASY;
DROP TABLE RANKING_MEDIUM;
DROP TABLE RANKING_HARD;

CREATE TABLE RANKING_EASY(
	ID_EASY SERIAL,
	NAME_EASY VARCHAR(50),
	SCORE_EASY 	int
);
INSERT INTO RANKING_EASY (NAME_EASY, SCORE_EASY) VALUES
('EASY_SARA', 90),
('EASY_BARTOSZ', 90);

SELECT * FROM RANKING_EASY
ORDER BY SCORE_EASY DESC;

CREATE TABLE RANKING_MEDIUM(
	ID_MEDIUM SERIAL,
	NAME_MEDIUM VARCHAR(50),
	SCORE_MEDIUM int
);
INSERT INTO RANKING_MEDIUM (NAME_MEDIUM, SCORE_MEDIUM) VALUES
('MEDIUM_SARA', 120),
('MEDIUM_BARTOSZ', 120);

SELECT * FROM RANKING_MEDIUM
ORDER BY SCORE_MEDIUM DESC;

CREATE TABLE RANKING_HARD(
	ID_HARD SERIAL,
	NAME_HARD VARCHAR(50),
	SCORE_HARD int
);
INSERT INTO RANKING_HARD (NAME_HARD, SCORE_HARD) VALUES
('HARD_SARA', 480),
('HARD_BARTOSZ', 480);

SELECT * FROM RANKING_HARD
ORDER BY SCORE_HARD DESC;